In [1]:
import tensorflow as tf

## Changing the Datatype of a tensor

In [3]:
# Create a new tensor with default datatype (float32)
B = tf.constant([2.7,5.6])
B.dtype

tf.float32

In [5]:
C = tf.constant([7,10])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [ ]:
# A 32-bit precision tensor, often referred to as a single-precision tensor, represents each 
# numerical value using 32 bits. It provides higher precision and a wider range of representable values 
# compared to a 16-bit precision tensor.

# On the other hand, a 16-bit precision tensor, often referred to as a half-precision tensor, 
# uses 16 bits to represent each numerical value. It offers reduced precision but consumes less memory 
# and can potentially lead to faster computations compared to a 32-bit tensor.

# Here are some key differences between 32-bit and 16-bit precision tensors:

# Precision: The main difference between the two is the precision of the numerical values they can represent. 
# A 32-bit tensor provides higher precision and can represent a wider range of values with more decimal places,
# while a 16-bit tensor has reduced precision and can represent fewer decimal places accurately.

# Memory Usage: A 16-bit tensor requires half the memory compared to a 32-bit tensor for storing the same number 
# of values. This reduced memory usage is beneficial when dealing with large-scale models or datasets 
# that have memory constraints.

# Computation Speed: Operations involving 16-bit tensors can potentially be faster compared to those 
# involving 32-bit tensors. This is because the reduced precision allows for more efficient memory access 
# and computation. However, the actual speedup may vary depending on the specific hardware and operations 
# being performed.

# Numerical Stability: Due to the reduced precision, 16-bit tensors can be more susceptible to 
# numerical instability, especially in scenarios where computations involve very small or 
# very large values or when performing iterative calculations. This can result in numerical errors 
# or loss of precision in the final results.

# In some cases, using 16-bit precision tensors can be advantageous, such as in deep learning applications
# where memory usage and computational speed are critical, and the reduced precision does not 
# significantly impact the model's performance. However, it's important to consider the trade-off between 
# precision and potential numerical issues when choosing between 32-bit and 16-bit precision tensors, 
# ensuring that the chosen precision meets the requirements of the specific application.

In [6]:
# Change from float 32 to float 16
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.7, 5.6], dtype=float16)>

In [7]:
D.dtype

tf.float16

In [8]:
# Change from int 32 to float 32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [9]:
E.dtype

tf.float32

In [10]:
F = tf.cast(E, dtype=tf.float16)
F

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

In [11]:
F.dtype

tf.float16