In [4]:
import tensorflow as tf

## Aggregating Tensors

#### Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [5]:
# Get the absolute values
A = tf.constant([-7,-10])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [6]:
tf.abs(A) # absolute values implies take all the negative values of one tensor and convert them to positive values

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

### Lets's Go through the following forms of aggregation: 
    . Get the minimum

    . Get the maximum

    . Get the mean of a tensor

    . Get the sum of a tensor

In [7]:
import numpy as np

In [8]:
# Create a random tensor with values between 0 and 100 of size 50
B = tf.constant(np.random.randint(0,100,size=50))
B

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([57,  9, 58, 53, 22, 43, 63, 86, 34, 96, 50, 86, 48, 49, 37, 99,  0,
       76, 28, 72, 91,  6, 62, 41, 45, 13, 93, 46, 35, 81,  1, 88, 89, 40,
       56, 24, 24, 66,  9, 49, 50, 40, 16, 59, 64, 49, 41, 98, 38, 92])>

In [9]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [12]:
B.shape

TensorShape([50])

In [13]:
B.ndim

1

In [14]:
# Find the minimum
tf.reduce_min(B)
# numpy se karna ho to: np.min(B)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [15]:
# Find the max
tf.reduce_max(B)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [16]:
# Find the mean
tf.reduce_mean(B)

<tf.Tensor: shape=(), dtype=int32, numpy=51>

In [17]:
# Find the sum
tf.reduce_sum(B)

<tf.Tensor: shape=(), dtype=int32, numpy=2572>