In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Lets create a random tensor having values between 0 and 100 of size 50
A = tf.constant(np.random.randint(0,100,size=50))
A

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([74, 89, 85, 41, 58, 31, 93, 45, 22, 22, 64, 61, 16, 21, 39, 17, 71,
       57,  1, 94, 57, 45,  3,  6, 92, 94, 92, 29, 80, 80, 70, 82, 90, 38,
       97, 13, 95, 45,  5, 12, 59, 19, 80,  2, 29, 64, 90, 17, 82, 90])>

In [3]:
# Lets find the variance
tf.reduce_variance(A) # this doesn't work 

AttributeError: module 'tensorflow' has no attribute 'reduce_variance'

In [ ]:
# TensorFlow Probability (TFP) is a probabilistic programming library built on top of TensorFlow, 
# an open-source machine learning framework developed by Google. TFP provides a collection of tools and algorithms 
# for probabilistic modeling and statistical inference. It combines the capabilities of TensorFlow for efficient computation 
# with the flexibility and expressiveness of probabilistic programming.

# Some key features of TensorFlow Probability include:

# Probabilistic layers: TFP allows you to build models using probabilistic layers, which can be used to define complex, 
# deep probabilistic models. These layers can capture uncertainty in the input data and provide probabilistic outputs.

# Distributions: TFP provides a wide range of probability distributions, such as normal, beta, gamma, and many others. 
# These distributions can be used to model uncertain quantities and can be combined to form more complex distributions.

# Bayesian inference: TFP supports Bayesian inference methods, such as Markov chain Monte Carlo (MCMC) and variational inference. 
# These methods allow you to estimate the posterior distribution of model parameters given observed data.

# Gradient-based optimization: TFP leverages TensorFlow's automatic differentiation capabilities to perform gradient-based optimization. 
# This allows you to train probabilistic models using techniques like maximum likelihood estimation or variational inference.

# Integration with TensorFlow ecosystem: TFP seamlessly integrates with TensorFlow, allowing you to combine probabilistic modeling 
# with traditional deep learning techniques. You can build hybrid models that combine deterministic and probabilistic components.

# Overall, TensorFlow Probability provides a powerful framework for probabilistic modeling and enables researchers and 
# practitioners to tackle a wide range of problems that involve uncertainty and probabilistic reasoning.

In [ ]:
# tfp.stats is a module within TensorFlow Probability (TFP) that provides various statistical functions and utilities. 
# It offers a collection of functions for computing statistics, probabilistic calculations, and other operations related 
# to probability distributions. Here are some commonly used functionalities provided by tfp.stats:

# Summary statistics: tfp.stats includes functions to compute summary statistics of data, such as mean, variance, standard deviation, 
# minimum, maximum, median, mode, and quantiles.

# Probability calculations: The module provides functions for evaluating the probability density function (PDF), 
# cumulative distribution function (CDF), survival function, and log-probability of various probability distributions. 
# These calculations are useful for performing statistical analysis and making probabilistic predictions.

# Percentile computations: tfp.stats offers functions to compute percentiles of a dataset, allowing you to determine values below 
# which a certain percentage of the data falls.

# Statistical tests: The module includes statistical tests such as t-tests, chi-square tests, Kolmogorov-Smirnov tests, and others. 
# These tests help evaluate hypotheses and assess the significance of observed differences or similarities in data.

# Random samplers: tfp.stats provides functions to generate random samples from various probability distributions. 
# These samplers are useful for simulation studies and generating synthetic data.

# Statistical metrics: The module offers functions to compute statistical metrics, such as the Kullback-Leibler divergence, 
# Bhattacharyya distance, and mutual information. These metrics are used to measure the similarity or dissimilarity between 
# probability distributions.

# Linear regression: tfp.stats includes functions for performing linear regression, estimating regression coefficients, 
# and making predictions using linear models.

# These are just some examples of the functionalities provided by tfp.stats. The module offers a wide range of statistical functions 
# and utilities to assist in data analysis, modeling, and inference within the TensorFlow Probability framework.

In [5]:
# To find the variance of our tensor, we need to access tensorflow probability
import tensorflow_probability as tfp
tfp.stats.variance(A)

<tf.Tensor: shape=(), dtype=int32, numpy=990>

In [6]:
# Find the standard deviation
tf.reduce_std(A)

AttributeError: module 'tensorflow' has no attribute 'reduce_std'

In [8]:
# tf.math.reduce_std(A) # thsi doesn't work too

# So what we can do here is lets typecast it to float32
tf.math.reduce_std(tf.cast(A, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.466402>