In [1]:
import tensorflow as tf
import numpy as np

## Squeezing a tensor(removing all single dimensions)

In [2]:
# Create a tensor to get started
A = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
A

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.4256767 , 0.09248567, 0.6984384 , 0.07398343, 0.7727158 ,
           0.12432873, 0.63084745, 0.7984086 , 0.77095735, 0.6262394 ,
           0.92460155, 0.9506029 , 0.4563607 , 0.77707946, 0.4713788 ,
           0.38674247, 0.6453681 , 0.8662467 , 0.41191506, 0.75378084,
           0.79064775, 0.71118295, 0.27561748, 0.21834934, 0.10369766,
           0.38217592, 0.8144841 , 0.9480742 , 0.13587463, 0.9821708 ,
           0.18929172, 0.18959296, 0.7567173 , 0.37537634, 0.6090721 ,
           0.8657476 , 0.12620127, 0.05649912, 0.93892956, 0.00101888,
           0.03675294, 0.27576196, 0.8683721 , 0.10478079, 0.46264243,
           0.44159305, 0.16460931, 0.87192416, 0.23824787, 0.87063384]]]]],
      dtype=float32)>

In [3]:
A.shape

TensorShape([1, 1, 1, 1, 50])

In [4]:
A_squeezed = tf.squeeze(A) # what squeeze does is it removes dimensions of size 1 from the shape of a tensor
A_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.4256767 , 0.09248567, 0.6984384 , 0.07398343, 0.7727158 ,
       0.12432873, 0.63084745, 0.7984086 , 0.77095735, 0.6262394 ,
       0.92460155, 0.9506029 , 0.4563607 , 0.77707946, 0.4713788 ,
       0.38674247, 0.6453681 , 0.8662467 , 0.41191506, 0.75378084,
       0.79064775, 0.71118295, 0.27561748, 0.21834934, 0.10369766,
       0.38217592, 0.8144841 , 0.9480742 , 0.13587463, 0.9821708 ,
       0.18929172, 0.18959296, 0.7567173 , 0.37537634, 0.6090721 ,
       0.8657476 , 0.12620127, 0.05649912, 0.93892956, 0.00101888,
       0.03675294, 0.27576196, 0.8683721 , 0.10478079, 0.46264243,
       0.44159305, 0.16460931, 0.87192416, 0.23824787, 0.87063384],
      dtype=float32)>

In [5]:
A_squeezed.shape

TensorShape([50])

### One Hot Encoding Tensors

In [6]:
# One hot encoding is a technique used to represent categorical variables as binary vectors. 
# In this encoding scheme, each category is represented by a binary vector with a length equal 
# to the number of categories in the variable. The vector contains all zeros except for the index that 
# corresponds to the category, which is marked with a one.

# Here's an example to illustrate the concept. Let's say we have a categorical variable "Color" with three categories: 
# "Red," "Green," and "Blue." 
# We can perform one hot encoding on this variable as follows:

# "Red" would be represented as [1, 0, 0]
# "Green" would be represented as [0, 1, 0]
# "Blue" would be represented as [0, 0, 1]
# Each category is assigned a unique binary vector, and the length of the vector is equal to the number of categories. 
# One hot encoding ensures that there is no ordinal relationship or numerical value associated with the categories; 
# it simply represents the presence or absence of a category.

# One hot encoding is commonly used in machine learning algorithms to handle categorical data since many algorithms operate 
# on numerical inputs. By converting categorical variables into numerical vectors, we can incorporate them into the models 
# and make them suitable for analysis or training.

In [7]:
# Create a list of indices
eg_list = [0,1,2,3] # could be red, green, blue, purple

# one hot encode our list of indices
tf.one_hot(eg_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [8]:
# Specify custom values for one hot encoding
tf.one_hot(eg_list, depth=4, on_value="Hi Guys!", off_value="Welcome to my stream.") # 0,1 ke jagah matrix mey new values aa jaayegi

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Hi Guys!', b'Welcome to my stream.', b'Welcome to my stream.',
        b'Welcome to my stream.'],
       [b'Welcome to my stream.', b'Hi Guys!', b'Welcome to my stream.',
        b'Welcome to my stream.'],
       [b'Welcome to my stream.', b'Welcome to my stream.', b'Hi Guys!',
        b'Welcome to my stream.'],
       [b'Welcome to my stream.', b'Welcome to my stream.',
        b'Welcome to my stream.', b'Hi Guys!']], dtype=object)>