In [1]:
import tensorflow as tf

## Squaring, Log, Square Root

In [2]:
# Crete a new tensor
A = tf.range(1,10)
A

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [3]:
# Square it
tf.square(A)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [5]:
# Find the square root
# tf.sqrt(A) # error will occur (method requires non-int type)

# So what we can do is lets typecast A and try sqrt 
tf.sqrt(tf.cast(A,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [6]:
# Find the log
tf.log(A)

AttributeError: module 'tensorflow' has no attribute 'log'

In [7]:
# Again same problem. SO we need to do Type Casting Again
tf.math.log(tf.cast(A, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays. 

In [8]:
import numpy as np

In [10]:
# Create a tensor directly from a NumPy array
B = tf.constant(np.array([3., 7., 10.]))
B

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [13]:
# Convert our tensor back to a NumPy array
np.array(B), type(np.array(B))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [14]:
# Convert tensor B to a NumPy array
B.numpy(), type(B.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [16]:
# B = tf.constant([3.])
# B.numpy()[0]

In [17]:
# The default types of each are slightly different
numpy_B = tf.constant(np.array([3.,7.,10.]))
tensor_B = tf.constant([3.,7.,10.])
# Check the datatypes of each
numpy_B.dtype, tensor_B.dtype

(tf.float64, tf.float32)