In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
# check the dimension of our vector
vector.ndim

1

In [8]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                     [7,10]]) #ek seperate list mey 2 list daalo agar 2 x 2 matrix chahiye to
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
matrix.ndim

2

In [11]:
another_matrix = tf.constant([[10., 7.],
                              [3., 3.],
                              [8., 9.]], dtype = tf.float16) # specify the datatype with dtype parameter
# storing this number will take less storag space on our computer due to 32 bit precision
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  3.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
# Whats's the number dimnesions of another_matrix
another_matrix.ndim


2

In [13]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [14]:
tensor.ndim

3

In [15]:
# What we have created so Far 

# * Scalar: A single number
# * Vector: A number with direction(eg: wind, speed and direction)
# * Matrix: A 2-Dimensional array of numbers
# * Tensor: An n-dimensionsal array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, 
#                                               a 1-Dimensional tensor is a vector)