In [1]:
import tensorflow as tf

In [4]:
# Creating tensors with tf.Variable
changebale_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10,7])
changebale_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [5]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [6]:
# Let's try change one of the elements in our changeable tensor
changebale_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
changebale_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [8]:
# How about we try .assign()
changebale_tensor[0].assign(7)
changebale_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [9]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [10]:
unchangeable_tensor[0] = 7 # same error as changeable_tensor

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [11]:
# Ab ek kaam karte hai .assign(7) use karke dekhte hai unchangeable ke saath
unchangeable_tensor[0].assign(7) # yaha to .assign() method bhi kaam kr ni kar rha hai
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [12]:
# what we learnt is if we use Variable tensors it can be modified
# But if we use Constant Tensor it cannot be modified