In [1]:
import tensorflow as tf

Note: Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFLow does this for you.
However, if in doubt, use tf.constant and change it later if needed

In [2]:
# Creating Random tensors

# Random tensors are tensors of some arbitrary size which contain random numbers.

In [3]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape = (3,2)) # values came from a normal distribution
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [5]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [6]:
# Are random_1 and random_2 equal?
random_1,random_2, random_1==random_2 # random1, aur random_2 print hoga and last mey hum check kr rhe hai ki random__1 == random_2 hai ya nahi?

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)