In [27]:
import tensorflow as tf

In [28]:
# Shuffle the order of elements in a tensor

In [29]:
# Shuffle a tensor (Valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [30]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [31]:
# tf.random.set_seed() function is used to set the seed for random number generation. 
# It is a way to control the randomness and make the execution of your TensorFlow code reproducible.

In [32]:
# Shuffle our non-shuffled Tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [33]:
# ek aur bar run kara kar dekhte hai
tf.random.shuffle(not_shuffled) # order change ho gya

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

In [34]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

## Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds.

This sets the global seed.

Its interactions with operation-level seeds is as follows:

1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.

2. If the graph-level seed is set, but the operation seed is not: 

    The system deterministically picks an operation seed in conjunction with the graph-level seed so that it gets a unique random sequence. Within the same version of tensorflow and the user code, this system is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both graph-level and operation-level seeds explicitly.

3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.

4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.