In [2]:
import tensorflow as tf

In [3]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [4]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [5]:
A.ndim

1

In [6]:
A = tf.constant(numpy_A, shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

In [7]:
A.ndim

2

In [8]:
# Getting information from tensors

# When dealing with tensors you probably want to be aware of the following attributes:

# * Shape: The length(number of elements) of each of the dimensions of a tensor.  Code: tensor.shape
# * Rank: The number of tensor dimensions. 
#         A scalar has rank 0, a vector has a rank 1, a matrix has a rank 2 and a tensor has a rank n.
#         Code: tensor.ndim
# * Axis or dimension: A particular dimension of a tensor.  Code: tensor[0], tensor[:,1].....
# * Size: The total number of items in the tensor.  Code: tf.size(tensor)

In [9]:
# Create a rank 4 tensor
rank_four_tensor = tf.zeros(shape=[2,3,4,5]) # 2 part mey tensor divided hai.
# har part mey 3 matrices hai
# har matrix mey 4 row aur 5 column hai
rank_four_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [10]:
rank_four_tensor[0] # tensor ka pehla part chahiye

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [11]:
rank_four_tensor.shape

TensorShape([2, 3, 4, 5])

In [12]:
rank_four_tensor.ndim

4

In [13]:
tf.size(rank_four_tensor) # this is used least often

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [15]:
# Get various attributes of our tensor
print("Datatype of every element: ",rank_four_tensor.dtype)
print("Number of dimensions(rank): ",rank_four_tensor.ndim)
print("Shape of tensor: ",rank_four_tensor.shape)
print("Elements along the 0 axis: ",rank_four_tensor.shape[0])
print("Elements along the last axis: ",rank_four_tensor.shape[-1])
print("Total number of elements in our tensor: ",tf.size(rank_four_tensor))
# if you don't want extra information as above and just want the exact number of elements in the tensor add .numpy() at the end
print("Total number of elements in our tensor(just the exact number no extra information): ",tf.size(rank_four_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions(rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor(just the exact number no extra information):  120
