In [9]:
import tensorflow as tf

## Indexing Tensors

### Tensors can be indexed just like Python Lists.

In [11]:
# Create a rank four tensor
rank_four_tensor = tf.zeros(shape=[2,3,4,5])
rank_four_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [15]:
eg_list = [1,2,3,4]
# getting the first two elements of the list
eg_list[:2]
# eg_list[::-1] # reversing a list

[1, 2]

In [16]:
# Get the first 2 elements of each dimension 
rank_four_tensor[:2,:2,:2,:2]
# explanation: 

# 2 out of 2 parts 
# each part has 3 matrices so 2 matrices from each part
# each matrix has 4 rows so 2 out of four rows
# each matrix has 5 columns so 2 out of 5 columns

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [17]:
# first element from the list
eg_list[:1]

[1]

In [19]:
# get all elements from the list
eg_list[:]

[1, 2, 3, 4]

In [18]:
# Get the first element from each dimension from each index except for the final one
rank_four_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [20]:
# if you want the same output as above i.e, want all the five columns you can use ':' as well
rank_four_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
# get the first element from each dimension except for the second last dimension i.e, you want all the rows
rank_four_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [22]:
# Create a rank 2 tensor (2 dimensions)
rank_two_tensor = tf.constant([[6,3],
                               [3,6]])
rank_two_tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 3],
       [3, 6]])>

In [23]:
rank_two_tensor.shape

TensorShape([2, 2])

In [24]:
rank_two_tensor.ndim

2

In [25]:
eg_list

[1, 2, 3, 4]

In [27]:
# Get thelast element of the list
eg_list[-1]

4

In [29]:
import numpy 

In [30]:
# Get the last element of each row of our rank 2 tensor
rank_two_tensor[:,-1]
# rank_two_tensor[:,-1].numpy()

array([3, 6])

In [ ]:
# In TensorFlow, tf.newaxis is a convenient way to add an extra dimension to a tensor. 
# It is used to reshape a tensor by inserting a new axis at the specified position. 
# This can be useful, for example, when you want to perform operations that require tensors of compatible shapes.

In [34]:
# Add in extra dimension to our rank 2 tensor
rank_three_tensor_front = rank_two_tensor[tf.newaxis,...]
rank_three_tensor_front # new dimension has been added in beginning
# if you want to add new dimension at the end 
rank_three_tensor_back = rank_two_tensor[...,tf.newaxis]
rank_three_tensor_back
# If you want to add new dimension in a particular position
rank_three_tensor_another = rank_two_tensor[:,tf.newaxis,:]
rank_three_tensor_another

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[6, 3]],

       [[3, 6]]])>

In [40]:
# Alternative to tf.newaxis 
tf.expand_dims(rank_two_tensor, axis=0) # add new dimension in first axis
tf.expand_dims(rank_two_tensor, axis=1) # add new dimension in middle axis
tf.expand_dims(rank_two_tensor, axis=2) # Add new dimension in final axis
tf.expand_dims(rank_two_tensor, axis=-1) # one more method for final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[6],
        [3]],

       [[3],
        [6]]])>

In [41]:
# Expand the 0-axis
tf.expand_dims(rank_two_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[6, 3],
        [3, 6]]])>

In [42]:
rank_two_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 3],
       [3, 6]])>