In [3]:
import tensorflow as tf

# Manipulating Tensors

### Basic Operations

In [10]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [11]:
# original tensor is unchanged
tensor
tensor_new = tensor + 10
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [12]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [13]:
# Substraction
tensor_sub = tensor - 2
tensor_sub

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]])>

In [14]:
# Multiplication
tensor_mul = tensor * 5
tensor_mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]])>

In [16]:
# Division
tensor_div = tensor / 2
tensor_div

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [17]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [ ]:
# tf.math is a module in TensorFlow that provides various mathematical operations and functions 
# for performing computations on tensors. It contains a wide range of mathematical operations, 
# including basic arithmetic operations, mathematical functions, and advanced operations.


# Here are some commonly used functionalities provided by tf.math:


# Arithmetic operations: tf.math.add, tf.math.subtract, tf.math.multiply, tf.math.divide, etc. 
# These functions perform element-wise addition, subtraction, multiplication, and division on tensors.


# Mathematical functions: tf.math.exp, tf.math.log, tf.math.sin, tf.math.cos, tf.math.sqrt, tf.math.pow, 
# tf.math.abs, etc. These functions apply element-wise mathematical operations like exponentiation, logarithm, 
# trigonometric functions, square root, absolute value, etc.


# Reduction operations: tf.math.reduce_sum, tf.math.reduce_mean, tf.math.reduce_max, tf.math.reduce_min, etc. 
# These functions compute reductions along specific dimensions of a tensor, such as sum, mean, maximum, 
# minimum, etc.


# Element-wise comparisons: tf.math.equal, tf.math.not_equal, tf.math.greater, tf.math.less, 
# tf.math.logical_and, tf.math.logical_or, etc. These functions perform element-wise comparisons 
# and return boolean tensors indicating the result of the comparison.


# Other operations: tf.math.argmax, tf.math.argmin, tf.math.cumsum, tf.math.cumprod, tf.math.log_softmax, 
# tf.math.sigmoid, tf.math.softmax, tf.math.tensordot, etc. These functions perform operations like finding 
# indices of maximum or minimum values, computing cumulative sum or product, applying softmax or 
# sigmoid activation, computing tensor dot product, etc.


# These are just a few examples of the operations available in tf.math. 
# The module provides a rich set of mathematical functions and operations that can be applied 
# to tensors in TensorFlow to perform various computations efficiently.

In [18]:
tensor # even after using tf.math function the original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>