In [2]:
import tensorflow as tf

# Matrix Multiplication

### In Machine Learning, Matrix multiplication is one of the most common tensor operations.

In [3]:
# Matrix multiplication is a fundamental operation in linear algebra that involves multiplying two matrices
# to obtain a new matrix. It is defined as follows:


# Given two matrices A and B, where A has dimensions (m x n) and B has dimensions (n x p), 
# the resulting matrix C obtained from matrix multiplication has dimensions (m x p). 
# Each element in the resulting matrix C is computed by taking the dot product of a row from matrix A 
# and a column from matrix B.


# To illustrate the process of matrix multiplication, let's consider an example:

# Given matrices A and B:

# A = [[a11, a12, a13],
#      [a21, a22, a23]]

# B = [[b11, b12],
#      [b21, b22],
#      [b31, b32]]


# Matrix can be computed as:

# C = [[a11*b11 + a12*b21 + a13*b31, a11*b12 + a12*b22 + a13*b32],
#      [a21*b11 + a22*b21 + a23*b31, a21*b12 + a22*b22 + a23*b32]]


# In this example, matrix A has dimensions (2 x 3), and matrix B has dimensions (3 x 2). 
# After performing the matrix multiplication, the resulting matrix C has dimensions (2 x 2).


# It's important to note that for matrix multiplication to be valid, 
# the number of columns in the first matrix (A) must be equal to the number of rows in the second matrix (B). 
# The resulting matrix will have dimensions equal to the number of rows in the first matrix (A) 
# and the number of columns in the second matrix (B).

In [6]:
# In TensorFlow, tf.linalg is a module that provides a collection of linear algebra operations 
# for working with tensors. It offers a wide range of functions to perform common linear algebra computations 
# efficiently.

# Here are some of the functionalities provided by tf.linalg:

# Matrix operations: tf.linalg.matmul, tf.linalg.matrix_transpose, tf.linalg.matrix_inverse, 
# tf.linalg.matrix_solve, etc. These functions allow you to perform matrix multiplication, matrix transposition,
# matrix inversion, and matrix solving operations, respectively.

# Decompositions: tf.linalg.cholesky, tf.linalg.qr, tf.linalg.svd, tf.linalg.eig, etc. 
# These functions compute various matrix decompositions, such as Cholesky decomposition, QR decomposition, 
# singular value decomposition (SVD), and eigenvalue decomposition.

# Norms and determinants: tf.linalg.norm, tf.linalg.matrix_determinant, tf.linalg.vector_norm, etc. 
# These functions calculate norms of tensors, determinants of matrices, and vector norms.

# Solvers: tf.linalg.solvers, tf.linalg.LinearOperator, etc. These components provide functionality for 
# solving linear systems of equations and linear operators.

# Other utilities: tf.linalg.diag, tf.linalg.eye, tf.linalg.band_part, tf.linalg.tensor_diag, etc. 
# These functions generate matrices with specific structures, such as diagonal matrices, identity matrices, 
# and banded matrices.

# These are just a few examples of the operations and utilities available in the tf.linalg module. 
# It offers a comprehensive set of linear algebra functions that enable efficient computation and manipulation 
# of tensors in TensorFlow, especially in tasks involving linear transformations, matrix operations, 
# and numerical computations in machine learning and scientific computing.

In [7]:
# In TensorFlow, tf.linalg.matmul is a function that computes the matrix multiplication of two tensors. 
# It is part of the tf.linalg module, which provides linear algebra operations for tensors.

# The tf.linalg.matmul function supports matrix multiplication between tensors of arbitrary dimensions, 
# as long as the dimensions align properly for matrix multiplication. The function takes two arguments, 
# the first being the left-hand-side tensor (A), and the second being the right-hand-side tensor (B).

# It's important to ensure that the dimensions of the input matrices align properly for matrix multiplication. 
# Specifically, the number of columns in the left-hand-side tensor (A) must be equal to the number of rows 
# in the right-hand-side tensor (B) for the multiplication to be valid.

In [8]:
# In TensorFlow, the tf.matmul() function is used for matrix multiplication of two tensors. 
# It is a general-purpose matrix multiplication operation that can handle tensors of various dimensions.

# It's important to note that tf.matmul() follows the rules of matrix multiplication, 
# where the number of columns in the left-hand-side tensor (A) must match the number of rows in 
# the right-hand-side tensor (B) for the multiplication to be valid. The function also supports broadcasting 
# for compatible dimensions.

# Besides matrix multiplication, tf.matmul() can handle other tensor types, 
# such as batches of matrices or higher-dimensional tensors. It performs matrix multiplication along 
# the last two dimensions of the input tensors and broadcasts the remaining dimensions when applicable.

# The tf.matmul() function is a versatile operation used in various deep learning tasks, 
# such as computing linear transformations, implementing neural networks, and performing tensor 
# contractions in tensor algebra.

In [9]:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [15]:
tf.matmul(tensor, tensor) # matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [12]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [11]:
tensor * tensor # What happens here is elements are getting multiplied elemment wise

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [13]:
# Now if you want to multiply matrices via python operator use @ operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [16]:
x = tf.matmul(tensor, tensor)
y = tensor @ tensor

In [21]:
x == y

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [23]:
# Create a (3,2) tensor
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

# Create another (3,2) tensor
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [26]:
# Try to matrix multiply tensors of same shape
# X @ Y # error: matrix size incompatible
# tf.matmul(X, Y) # error: matrix size incomaptible