In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Let's create a classification dataset
from sklearn.datasets import make_circles

# Set n_samples to 1000
n_samples = 1000

# Feaures and Labels
X,y = make_circles(n_samples,
                   noise=0.03,
                   random_state=42)

In [3]:
X, y[:10]

(array([[ 0.75424625,  0.23148074],
        [-0.75615888,  0.15325888],
        [-0.81539193,  0.17328203],
        ...,
        [-0.13690036, -0.81001183],
        [ 0.67036156, -0.76750154],
        [ 0.28105665,  0.96382443]]),
 array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0], dtype=int64))

In [4]:
len(X)

1000

In [5]:
# Split the datset into training and testing data
X_train, y_train = X[:800], y[:800]
X_test, y_test = X[800:], y[800:]

In [6]:
# Let's build a model

# Set random seed
tf.random.set_seed(42)

# 1. Create a model using Sequential API
model = tf.keras.Sequential([
    tf.keras.layers.Dense(4, activation="relu"),
    tf.keras.layers.Dense(4, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

# 2. Compile the model
model.compile(loss="binary_crossentropy",
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.02),
              metrics=['accuracy'])

# 3.  Fit the model
model.fit(X_train, y_train, epochs=20, verbose=1)

Epoch 1/20
25/25 [==============================] - 0s 875us/step - loss: 0.6929 - accuracy: 0.5013
Epoch 2/20
25/25 [==============================] - 0s 699us/step - loss: 0.6824 - accuracy: 0.5475
Epoch 3/20
25/25 [==============================] - 0s 708us/step - loss: 0.6678 - accuracy: 0.5675
Epoch 4/20
25/25 [==============================] - 0s 667us/step - loss: 0.6421 - accuracy: 0.6112
Epoch 5/20
25/25 [==============================] - 0s 709us/step - loss: 0.5906 - accuracy: 0.7125
Epoch 6/20
25/25 [==============================] - 0s 792us/step - loss: 0.4984 - accuracy: 0.7912
Epoch 7/20
25/25 [==============================] - 0s 751us/step - loss: 0.4512 - accuracy: 0.8175
Epoch 8/20
25/25 [==============================] - 0s 708us/step - loss: 0.4052 - accuracy: 0.8363
Epoch 9/20
25/25 [==============================] - 0s 708us/step - loss: 0.3536 - accuracy: 0.8875
Epoch 10/20
25/25 [==============================] - 0s 750us/step - loss: 0.2955 - accuracy: 0.9400

In [7]:
# Check the accuracy of our model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Model loss on test set: {loss}")
print(f"Model accuracy on test set {(accuracy*100):.2f}%")

7/7 [==============================] - 0s 1ms/step - loss: 0.1437 - accuracy: 0.9550
Model loss on test set: 0.1436844766139984
Model accuracy on test set 95.50%


In [ ]:
# Create a confusion matrix
from sklearn.metrics import confusion_matrix

# Make predictions
y_preds = model.predict(X_test)

# Create confusion matrix
confusion_matrix(y_test, y_preds)

The above code will result in a error 

It seems our predictions aren't in the format they need to be.

In [9]:
# View the first 10 predicions
y_preds[:10]

array([[0.91204727],
       [0.9821358 ],
       [0.9915107 ],
       [0.9792727 ],
       [0.7554331 ],
       [0.14507754],
       [0.86407834],
       [0.11832591],
       [0.9744899 ],
       [0.02278617]], dtype=float32)

What about our test labels?

In [10]:
# View the first 10 test labels
y_test[:10]

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int64)