In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Create Data
X = tf.range(-100,100,4)
X

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([-100,  -96,  -92,  -88,  -84,  -80,  -76,  -72,  -68,  -64,  -60,
        -56,  -52,  -48,  -44,  -40,  -36,  -32,  -28,  -24,  -20,  -16,
        -12,   -8,   -4,    0,    4,    8,   12,   16,   20,   24,   28,
         32,   36,   40,   44,   48,   52,   56,   60,   64,   68,   72,
         76,   80,   84,   88,   92,   96])>

In [4]:
y = X + 10
y

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([-90, -86, -82, -78, -74, -70, -66, -62, -58, -54, -50, -46, -42,
       -38, -34, -30, -26, -22, -18, -14, -10,  -6,  -2,   2,   6,  10,
        14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,  58,  62,
        66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106])>

In [5]:
X_train = X[:40]
X_test = X[40:]

y_train = y[:40]
y_test = y[40:]

In [6]:
X_train, X_test, y_train, y_test

(<tf.Tensor: shape=(40,), dtype=int32, numpy=
 array([-100,  -96,  -92,  -88,  -84,  -80,  -76,  -72,  -68,  -64,  -60,
         -56,  -52,  -48,  -44,  -40,  -36,  -32,  -28,  -24,  -20,  -16,
         -12,   -8,   -4,    0,    4,    8,   12,   16,   20,   24,   28,
          32,   36,   40,   44,   48,   52,   56])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([60, 64, 68, 72, 76, 80, 84, 88, 92, 96])>,
 <tf.Tensor: shape=(40,), dtype=int32, numpy=
 array([-90, -86, -82, -78, -74, -70, -66, -62, -58, -54, -50, -46, -42,
        -38, -34, -30, -26, -22, -18, -14, -10,  -6,  -2,   2,   6,  10,
         14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,  58,  62,
         66])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 70,  74,  78,  82,  86,  90,  94,  98, 102, 106])>)

In [7]:
len(X_train), len(X_test), len(y_train), len(y_test)

(40, 10, 40, 10)

## Comparing the results of our experiments

    Let's build 3 models again to compare

In [8]:
# Model 1
tf.random.set_seed(42)

# 1. Create a model
model_1 = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])

# 2. compile the model
model_1.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.SGD(),
                metrics=['mae'])

# 3. Fit the model
model_1.fit(tf.expand_dims(X_train, axis= -1), y_train, epochs=100)

Epoch 1/100
2/2 [==============================] - 0s 4ms/step - loss: 88.0227 - mae: 88.0227
Epoch 2/100
2/2 [==============================] - 0s 2ms/step - loss: 52.5673 - mae: 52.5673
Epoch 3/100
2/2 [==============================] - 0s 2ms/step - loss: 16.9641 - mae: 16.9641
Epoch 4/100
2/2 [==============================] - 0s 2ms/step - loss: 9.2009 - mae: 9.2009
Epoch 5/100
2/2 [==============================] - 0s 3ms/step - loss: 10.9921 - mae: 10.9921
Epoch 6/100
2/2 [==============================] - 0s 2ms/step - loss: 10.1596 - mae: 10.1596
Epoch 7/100
2/2 [==============================] - 0s 3ms/step - loss: 9.1835 - mae: 9.1835
Epoch 8/100
2/2 [==============================] - 0s 2ms/step - loss: 9.1417 - mae: 9.1417
Epoch 9/100
2/2 [==============================] - 0s 4ms/step - loss: 15.1950 - mae: 15.1950
Epoch 10/100
2/2 [==============================] - 0s 2ms/step - loss: 7.8576 - mae: 7.8576
Epoch 11/100
2/2 [==============================] - 0s 3ms/step - l

In [9]:
model_1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2 (8.00 Byte)
Trainable params: 2 (8.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
pred_1 = model_1.predict(X_test)
pred_1

1/1 [==============================] - 0s 61ms/step


array([[ 74.55136 ],
       [ 79.437   ],
       [ 84.32263 ],
       [ 89.20826 ],
       [ 94.093895],
       [ 98.97952 ],
       [103.86516 ],
       [108.75079 ],
       [113.63642 ],
       [118.52206 ]], dtype=float32)

In [11]:
# Model 2

tf.random.set_seed(42)

# 1. Create a model 
model_2 = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

# 2. Compile a model
model_2.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.SGD(),
                metrics=['mae'])

# 3. Fit the model
model_2.fit(tf.expand_dims(X_train, axis= -1), y_train, epochs=100)

Epoch 1/100
2/2 [==============================] - 0s 4ms/step - loss: 29.5528 - mae: 29.5528
Epoch 2/100
2/2 [==============================] - 0s 2ms/step - loss: 26.5915 - mae: 26.5915
Epoch 3/100
2/2 [==============================] - 0s 2ms/step - loss: 30.1673 - mae: 30.1673
Epoch 4/100
2/2 [==============================] - 0s 2ms/step - loss: 16.2693 - mae: 16.2693
Epoch 5/100
2/2 [==============================] - 0s 3ms/step - loss: 22.2362 - mae: 22.2362
Epoch 6/100
2/2 [==============================] - 0s 2ms/step - loss: 11.4673 - mae: 11.4673
Epoch 7/100
2/2 [==============================] - 0s 2ms/step - loss: 12.5522 - mae: 12.5522
Epoch 8/100
2/2 [==============================] - 0s 2ms/step - loss: 11.0705 - mae: 11.0705
Epoch 9/100
2/2 [==============================] - 0s 2ms/step - loss: 39.7426 - mae: 39.7426
Epoch 10/100
2/2 [==============================] - 0s 2ms/step - loss: 27.2314 - mae: 27.2314
Epoch 11/100
2/2 [==============================] - 0s 2ms/

In [12]:
model_2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 10)                20        
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
y_pred_2 = model_2.predict(X_test)
y_pred_2

1/1 [==============================] - 0s 28ms/step


array([[ 70.30203 ],
       [ 74.875305],
       [ 79.44858 ],
       [ 84.02185 ],
       [ 88.59514 ],
       [ 93.16841 ],
       [ 97.74168 ],
       [102.31496 ],
       [106.88822 ],
       [111.46152 ]], dtype=float32)

In [14]:
# Model 3

tf.random.set_seed(42)

# 1. Create a model
model_3 = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

# 2. Compile a model
model_3.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.SGD(),
                metrics=['mae'])

# 3. Fit the model
model_3.fit(tf.expand_dims(X_train, axis= -1), y_train, epochs=500)

Epoch 1/500
2/2 [==============================] - 0s 0s/step - loss: 27.8673 - mae: 27.8673
Epoch 2/500
2/2 [==============================] - 0s 0s/step - loss: 25.5923 - mae: 25.5923
Epoch 3/500
2/2 [==============================] - 0s 0s/step - loss: 29.5437 - mae: 29.5437
Epoch 4/500
2/2 [==============================] - 0s 2ms/step - loss: 16.5988 - mae: 16.5988
Epoch 5/500
2/2 [==============================] - 0s 3ms/step - loss: 19.1894 - mae: 19.1894
Epoch 6/500
2/2 [==============================] - 0s 2ms/step - loss: 13.5350 - mae: 13.5350
Epoch 7/500
2/2 [==============================] - 0s 1ms/step - loss: 12.7071 - mae: 12.7071
Epoch 8/500
2/2 [==============================] - 0s 3ms/step - loss: 11.0942 - mae: 11.0942
Epoch 9/500
2/2 [==============================] - 0s 3ms/step - loss: 40.1781 - mae: 40.1781
Epoch 10/500
2/2 [==============================] - 0s 3ms/step - loss: 27.6110 - mae: 27.6110
Epoch 11/500
2/2 [==============================] - 0s 3ms/ste

In [15]:
model_3.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 10)                20        
                                                                 
 dense_4 (Dense)             (None, 1)                 11        
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
y_pred_3 = model_3.predict(X_test)
y_pred_3

1/1 [==============================] - 0s 13ms/step


array([[16.34796 ],
       [17.142284],
       [17.93661 ],
       [18.73093 ],
       [19.525253],
       [20.319576],
       [21.113901],
       [21.908224],
       [22.702547],
       [23.49687 ]], dtype=float32)

In [17]:
# Lets create a function to evaluate our model
def mae(y_true, y_pred):
    return tf.metrics.mean_absolute_error(y_true, tf.squeeze(y_pred))
def mse(y_true, y_pred):
    return tf.metrics.mean_squared_error(y_true, tf.squeeze(y_pred))

In [18]:
mae_1 = mae(y_test, pred_1)
mse_1 = mse(y_test, pred_1)

mae_2 = mae(y_test, y_pred_2)
mse_2 = mse(y_test, y_pred_2)

mae_3 = mae(y_test, y_pred_3)
mse_3 = mse(y_test, y_pred_3)

In [19]:
mae_1, mae_2, mae_3

(<tf.Tensor: shape=(), dtype=float32, numpy=8.53671>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.8817687>,
 <tf.Tensor: shape=(), dtype=float32, numpy=68.07759>)

In [20]:
mse_1, mse_2, mse_3

(<tf.Tensor: shape=(), dtype=float32, numpy=79.34625>,
 <tf.Tensor: shape=(), dtype=float32, numpy=11.015909>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4719.3374>)

    Note: You want to start with small experiments(small models) and make sure they work and then increase their scale when necessary 

#### We have run a few experiments, let's compare the results.

In [22]:
# Let's compare our model's results using pandas DataFrame
import pandas as pd

model_results = [["model_1", mae_1, mse_1],
                 ["model_2", mae_2, mse_2],
                 ["model_3", mae_3, mse_3]]

all_results = pd.DataFrame(model_results, columns=["model", "mae", "mse"]) 
all_results # Output mey bahut saari cheeze aa rhi hai jaise tensor, dtype, etc. Ab vo sab hatana hai and sirf 
# aapke table mey numbers show karwane hai to use .numpy()

model                                            mae   
0  model_1    tf.Tensor(8.53671, shape=(), dtype=float32)  \
1  model_2  tf.Tensor(2.8817687, shape=(), dtype=float32)   
2  model_3   tf.Tensor(68.07759, shape=(), dtype=float32)   

                                             mse  
0   tf.Tensor(79.34625, shape=(), dtype=float32)  
1  tf.Tensor(11.015909, shape=(), dtype=float32)  
2  tf.Tensor(4719.3374, shape=(), dtype=float32)

In [24]:
model_results = [["model_1", mae_1.numpy(), mse_1.numpy()],
                 ["model_2", mae_2.numpy(), mse_2.numpy()],
                 ["model_3", mae_3.numpy(), mse_3.numpy()]]

all_results = pd.DataFrame(model_results, columns=["model", "mae", "mse"])
all_results

model        mae          mse
0  model_1   8.536710    79.346252
1  model_2   2.881769    11.015909
2  model_3  68.077591  4719.337402

In [25]:
# Model 2 performed the best. So let's check
model_2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 10)                20        
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


    Note: One of your main goal should be to minimize the time between your experiments. The more experiments you do, the more things you'll figure out which doesn't work and in turn, get closer to figuring out what does work.

    Remember the machine learning practitioner's motto: "experiment, experiment, experiment".