In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X = tf.range(-100, 100, 4)

y = X + 10

X, y

(<tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([-100,  -96,  -92,  -88,  -84,  -80,  -76,  -72,  -68,  -64,  -60,
         -56,  -52,  -48,  -44,  -40,  -36,  -32,  -28,  -24,  -20,  -16,
         -12,   -8,   -4,    0,    4,    8,   12,   16,   20,   24,   28,
          32,   36,   40,   44,   48,   52,   56,   60,   64,   68,   72,
          76,   80,   84,   88,   92,   96])>,
 <tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([-90, -86, -82, -78, -74, -70, -66, -62, -58, -54, -50, -46, -42,
        -38, -34, -30, -26, -22, -18, -14, -10,  -6,  -2,   2,   6,  10,
         14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,  58,  62,
         66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106])>)

In [4]:
X_train = X[:40]
y_train = y[:40]

X_test = X[40:]
y_test = y[40:]

X_train, y_train, X_test, y_test

(<tf.Tensor: shape=(40,), dtype=int32, numpy=
 array([-100,  -96,  -92,  -88,  -84,  -80,  -76,  -72,  -68,  -64,  -60,
         -56,  -52,  -48,  -44,  -40,  -36,  -32,  -28,  -24,  -20,  -16,
         -12,   -8,   -4,    0,    4,    8,   12,   16,   20,   24,   28,
          32,   36,   40,   44,   48,   52,   56])>,
 <tf.Tensor: shape=(40,), dtype=int32, numpy=
 array([-90, -86, -82, -78, -74, -70, -66, -62, -58, -54, -50, -46, -42,
        -38, -34, -30, -26, -22, -18, -14, -10,  -6,  -2,   2,   6,  10,
         14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,  58,  62,
         66])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([60, 64, 68, 72, 76, 80, 84, 88, 92, 96])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 70,  74,  78,  82,  86,  90,  94,  98, 102, 106])>)

## Saving Our Models

    Saving our models allows us to use them outside of VSCode, Google Colab (or wherever they were trained) such as in a web application or a mobile app.

    There are two main formats we can save our models too:

    1. The SaveModel format
    2. The HDF5 format

In [5]:
# Let's build a model

tf.random.set_seed(42)

# 1. Create a model
model_2 = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

# 2. Compile the model
model_2.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.SGD(),
                metrics=['mae'])

# 3. Fit the model
model_2.fit(tf.expand_dims(X_train, axis= -1), y_train, epochs=100)

Epoch 1/100
2/2 [==============================] - 0s 6ms/step - loss: 41.4072 - mae: 41.4072
Epoch 2/100
2/2 [==============================] - 0s 3ms/step - loss: 31.5937 - mae: 31.5937
Epoch 3/100
2/2 [==============================] - 0s 3ms/step - loss: 36.8485 - mae: 36.8485
Epoch 4/100
2/2 [==============================] - 0s 2ms/step - loss: 26.4012 - mae: 26.4012
Epoch 5/100
2/2 [==============================] - 0s 3ms/step - loss: 14.4818 - mae: 14.4818
Epoch 6/100
2/2 [==============================] - 0s 2ms/step - loss: 11.5745 - mae: 11.5745
Epoch 7/100
2/2 [==============================] - 0s 2ms/step - loss: 12.6402 - mae: 12.6402
Epoch 8/100
2/2 [==============================] - 0s 3ms/step - loss: 11.0509 - mae: 11.0509
Epoch 9/100
2/2 [==============================] - 0s 4ms/step - loss: 39.7576 - mae: 39.7576
Epoch 10/100
2/2 [==============================] - 0s 3ms/step - loss: 27.2430 - mae: 27.2430
Epoch 11/100
2/2 [==============================] - 0s 3ms/

In [6]:
# Save the model using the SavedModel format
model_2.save("best_model_SavedModel_format")

INFO:tensorflow:Assets written to: best_model_SavedModel_format\assets


INFO:tensorflow:Assets written to: best_model_SavedModel_format\assets


In [ ]:
# Save model using HDF5 format
model_2.save("best_model_HDF5_format.h5")

In [8]:
model_2.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                20        
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
