In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = tf.range(-100, 100, 4)

y = X + 10

X, y

(<tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([-100,  -96,  -92,  -88,  -84,  -80,  -76,  -72,  -68,  -64,  -60,
         -56,  -52,  -48,  -44,  -40,  -36,  -32,  -28,  -24,  -20,  -16,
         -12,   -8,   -4,    0,    4,    8,   12,   16,   20,   24,   28,
          32,   36,   40,   44,   48,   52,   56,   60,   64,   68,   72,
          76,   80,   84,   88,   92,   96])>,
 <tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([-90, -86, -82, -78, -74, -70, -66, -62, -58, -54, -50, -46, -42,
        -38, -34, -30, -26, -22, -18, -14, -10,  -6,  -2,   2,   6,  10,
         14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,  58,  62,
         66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106])>)

In [4]:
X_train = X[:40]
y_train = y[:40]

X_test = X[40:]
y_test = y[40:]

In [5]:
X_train, X_test, y_train, y_test

(<tf.Tensor: shape=(40,), dtype=int32, numpy=
 array([-100,  -96,  -92,  -88,  -84,  -80,  -76,  -72,  -68,  -64,  -60,
         -56,  -52,  -48,  -44,  -40,  -36,  -32,  -28,  -24,  -20,  -16,
         -12,   -8,   -4,    0,    4,    8,   12,   16,   20,   24,   28,
          32,   36,   40,   44,   48,   52,   56])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([60, 64, 68, 72, 76, 80, 84, 88, 92, 96])>,
 <tf.Tensor: shape=(40,), dtype=int32, numpy=
 array([-90, -86, -82, -78, -74, -70, -66, -62, -58, -54, -50, -46, -42,
        -38, -34, -30, -26, -22, -18, -14, -10,  -6,  -2,   2,   6,  10,
         14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,  58,  62,
         66])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 70,  74,  78,  82,  86,  90,  94,  98, 102, 106])>)

In [7]:
# Let's build a model

tf.random.set_seed(42)

# 1. Create a Model
model_2 = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
], name="TensorFlow_39")

# 2. Compile a model
model_2.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.SGD(),
                metrics=['mae'])

# 3. Fit the model
model_2.fit(tf.expand_dims(X_train, axis= -1), y_train, epochs=100)

Epoch 1/100
2/2 [==============================] - 0s 4ms/step - loss: 62.5021 - mae: 62.5021
Epoch 2/100
2/2 [==============================] - 0s 1ms/step - loss: 26.3730 - mae: 26.3730
Epoch 3/100
2/2 [==============================] - 0s 3ms/step - loss: 19.1524 - mae: 19.1524
Epoch 4/100
2/2 [==============================] - 0s 1ms/step - loss: 13.8818 - mae: 13.8818
Epoch 5/100
2/2 [==============================] - 0s 2ms/step - loss: 15.3985 - mae: 15.3985
Epoch 6/100
2/2 [==============================] - 0s 3ms/step - loss: 12.2246 - mae: 12.2246
Epoch 7/100
2/2 [==============================] - 0s 3ms/step - loss: 11.5188 - mae: 11.5188
Epoch 8/100
2/2 [==============================] - 0s 2ms/step - loss: 11.2260 - mae: 11.2260
Epoch 9/100
2/2 [==============================] - 0s 3ms/step - loss: 41.9975 - mae: 41.9975
Epoch 10/100
2/2 [==============================] - 0s 1ms/step - loss: 29.1948 - mae: 29.1948
Epoch 11/100
2/2 [==============================] - 0s 2ms/

In [8]:
# Create Evaluation function 
def mae(y_true, y_pred):
    return tf.metrics.mean_absolute_error(y_true, tf.squeeze(y_pred))

def mse(y_true, y_pred):
    return tf.metrics.mean_squared_error(y_true, tf.squeeze(y_pred))

In [10]:
model_2_preds = model_2.predict(X_test)
model_2_preds

1/1 [==============================] - 0s 42ms/step


array([[ 78.20319 ],
       [ 83.301994],
       [ 88.400795],
       [ 93.49959 ],
       [ 98.59839 ],
       [103.6972  ],
       [108.796   ],
       [113.89479 ],
       [118.99359 ],
       [124.0924  ]], dtype=float32)

In [11]:
# Load model
loaded_SaveModel_format = tf.keras.models.load_model("best_model_SavedModel_format")
loaded_SaveModel_format.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                20        
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
loaded_SaveModel_format_preds = loaded_SaveModel_format.predict(X_test)

1/1 [==============================] - 0s 17ms/step


In [14]:
mae(y_true=y_test, y_pred=model_2_preds) == mae(y_true=y_test, y_pred=loaded_SaveModel_format_preds)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

## Download a model (or any other file) from Google Colab

If you want to download your files from Google Colab: 